### PR TITLE
[ISSUE 299] Set up front-end infrastructure in AWS

### LINKED ISSUE #299: [Task]: Set up front-end infrastructure in AWS
### Summary

We will use Terraform and Github Actions to spin up infrastructure for the front-end on AWS.

Set up dev + prod environments on same account. Either front-end or back-end, whichever comes first, will also be responsible for setting up higher level infra.

Related to #189 
Blocked by #188 
Unblocks to #285 

### Acceptance criteria

- [ ] Follow `template-infra` conventions to build and deploy architecture to AWS
- [ ] Redeploys on changes to `/frontend` via Github Actions
- [ ] Test/verify via AWS console

### PR DESCRIPTION
**Pull request by daphnegold**
## Summary
Fixes #299

## Changes proposed
Integrates https://github.com/navapbc/template-infra into grants-equity

## Context for reviewers
Infrastructure has been deployed to AWS and front-end app is running there in dev cluster. Includes account level infrastructure. :)

http://frontend-dev-143463875.us-east-1.elb.amazonaws.com/

Screenshot 2023-08-22 at 3 07 02 PM

### CODE REVIEW

**Review by acouch — COMMENTED** [review]
Amazing work and progress!

(blocking): We need to address the `docs/` folder.  Ultimately it would be integrated with the `documentation` folder.  

For this PR I think we could remove the `docs/` folder and create a separate ticket to properly integrate it, or integrate the folder in this PR.

The `docs/infra` folder could be moved to `documentation/infra` or `documentation/architecture`. The ADRs should have a happy home in `documentation/decisions/`, but that could be its own PR as well. 

If there is energy to integrate the `docs` in this PR, would work as well.

**Comment by daphnegold** [comment]
> (blocking): We need to address the `docs/` folder. Ultimately it would be integrated with the `documentation` folder.

This doesn't need to be blocking for this PR, if we are planning to have a follow up PR for it to address organization. I figured there'd be opinions on that. It can be dragged and dropped anywhere at any time.

**Review by acouch — COMMENTED** [review]
suggestion (blocking):

The `documentation/decisions/infra` are not formatted in the same way as the others. We have also not discussed whether to separate ADRs into separate folders AFAIK. I would recommend removing the infra ADRs for another ticket or to include the ADRs in the newer date format.

`documentation/infra/infra` material could be moved to `documentation/infra` and the redundant `infra/infra` folder removed.

I would recommend removing `/documentation/infra/code-reviews.md` and `releases.md` as is infra specific.

**Comment by daphnegold** [comment]
> suggestion (blocking):
> 
> The `documentation/decisions/infra` are not formatted in the same way as the others. We have also not discussed whether to separate ADRs into separate folders AFAIK. I would recommend removing the infra ADRs for another ticket or to include the ADRs in the newer date format.

Actually don't think it's worthwhile to change the format. We are just creating more busy work for ourselves whenever we pull in changes from the infrastructure template. The format doesn't need to be blocking, does it? Also don't think it's worthwhile blocking this PR based on a discussion on if it's okay to have sub-folders in our ADR directory.

**Review by acouch — APPROVED** [review]
Thanks for updating the docs folder. Looks a lot cleaner now. I think the difference in format introduces a new change that could be best handled in a separate ticket. I would typically hold off on introducing that change until the ticket is created, but don't want to hold up this amazing work. Let's discuss when we get a chance.

**Pull request merged**
